- shell:
    - [mkdir -p ~/Bilder/Screenshots, Creating screenshots directory]
    - [mkdir -p ~/Videos/Screencasts, Creating screencasts directory]
    - [mkdir -p ~/Dokumente/Pastes, Creating pastes directory]

- link:
    ~/.config/teiler: tools/misc/teiler
#  vim: set filetype=yaml ts=4 sw=4 tw=0 et :
