- link:
    ~/.vim:         editors/vim
    ~/.vimrc:       editors/vim/vimrc
    ~/.config/nvim: editors/vim

- shell:
    - [vim -c 'PlugInstall' +qall || true, Installing vim plugins]
#  vim: set filetype=yaml ts=4 sw=4 tw=0 et :
